### ISSUE TITLE
Vagrant up gets messed up by the ServerPilot root warning login message.

### ISSUE THREAD

**Issue by martyp187** [Xety/ServerPilot#1]
Hi, When using this as a base for getting a ServerPilot box up I could not get things like the synced files to work. No error message as such, but it was if the file was not being read that far.

Long story short, it looks like the "Careful you are logged in as root.." script the Server Pilot installer added to /profile.d causes the up process to miss some commands (like sync folder setup)

I'm really new to Vagrant. Is there anything that can be done to fix this? Or anything added to remove that script file before root commands are run?

**Comment by Vandaahl** [comment]
Did you find a fix for this? I'm having the same problem of synced folders not working.

**Comment by martyp187** [comment]
I actually just deleted the script from that directory so it couldn't trigger.

**Comment by Vandaahl** [comment]
Thanks, I did the same and now it works. I only have this issue on OS X by the way. Windows works like a charm right away.
